version: '2.20.3' # Выводится командой docker compose version

services:
  server:
    image: gracield/nginx:v3
    container_name: server
    tty: true # держит контейнер в рабочем состоянии
    user: root

  nginx-proxy:
    image: nginx:latest
    ports:
     - 80:8080
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: part_6
    tty: true
